#!/usr/bin/env bash
# Tranfer a file from client to server

display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4
if [ $# -lt 4 ]; then
    display_usage
    exit 1
fi

# Assign arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4
