#!/bin/bash

# Update package index and install Nginx
sudo apt update
sudo apt install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Create a temporary HTML file with Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx
sudo service nginx restart
