#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

if ! dpkg -l | grep -q nginx; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF

sudo ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t

sudo service nginx restart

rm /etc/nginx/sites-available/redirect_me

echo "Redirection configured successfully."
