#!/usr/bin/env bash
# Configure web-01 to have an http response header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/ZamamboGcwabe permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "server_name _;/a add_header X-Serverd-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
