#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  imvuselelo-tech-frontend
        bind *:80
        mode http
        default_backend imvuselelo-tech-backend
backend imvuselelo-tech-backend
        balance roundrobin
        server 248075--web-01 18.235.255.27:80 check
        server 248075--web-02 52.91.133.214:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
