#!/usr/bin/env bash
# Config nginx to listen to port 80

apt-get update
apt-get -y install nginx
sed -i 's/80 default_server/80 default_server ipv4only=on/g' /etc/nginx/sites-available/default
service nginx restart
