#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China
# displays 9 and then bad luck from Japan
# displays 17 and then bad luck from Italy

number=1

while [ $counter -le 20 ]
do
echo "$counter"
case $counter in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
ecas
(( counter++ ))
done
