#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Only the part of the name after the first dash
for file in *;
do
if [ -f "$file" ] && [[ "$file" != .* ]];
then
name=$( echo "$file" | cut -d '-' -f 2- )
echo "$name"
fi
done
